# Generated by Django 2.2.24 on 2021-08-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de Creción')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de modificación')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('disabled_at', models.DateTimeField(blank=True, default=None, help_text='Fecha de modificación', null=True)),
                ('status', models.CharField(max_length=35, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
    ]
