# Generated by Django 2.2.24 on 2021-08-04 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de Creción')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de modificación')),
                ('schedule', models.DateTimeField(help_text='Fecha de agenda')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('status', models.CharField(max_length=35, verbose_name='Status')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
