# Generated by Django 2.2.24 on 2021-08-04 05:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Respuestas')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de Creción')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Activity', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
            },
        ),
    ]
